### ISSUE TITLE
add optional blackd support

### ISSUE THREAD

**Issue by satyajeet-sundial** [wbolster/emacs-python-black#8] opened 2021-09-14 13:44 UTC
right now, running `black` on every save can be slow.

`black` has an optional add-on through `pip install black[d]` which runs a small server and can be faster than spawning a new process everytime.

https://black.readthedocs.io/en/stable/usage_and_configuration/black_as_a_server.html

emacs-python-black could support this interface in addition to calling the black program for faster formatting.

**Comment by wbolster** [comment] 2021-09-14 16:13
hi, thanks for you message.

i can see how this may be useful, but the added complexity needed for this is way more than i would like in this (trivial by design) emacs package. it would mean moving away from `reformatter.el`, which i don't want to since it's great, or writing a custom executable (and dealing with the complexity of installing and running that), because, as the page you linked to, notes:

> There is no official `blackd` client tool (yet!).

so at this point i lean towards ‘wontfix’ for this.

**Closed as completed by wbolster** 2021-09-14 16:13 UTC
Labels: enhancement, wontfix

**Comment by satyajeet-sundial** [comment] 2021-09-14 16:20
@wbolster alright, you're right in that the `black` command should automatically "know" if a daemon is running and use that instead of doing the formatting itself.
